name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    name: Build & Scan Docker Image
    runs-on: ubuntu-latest

steps:
      - name: Checkout Code
        uses: actions/checkout@v4

- name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

- name: Build Docker Image
        run: docker build -t devsecops-app .

- name: Install Trivy
        run: |
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar zxvf trivy_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

- name: Scan Docker Image with Trivy
        run: trivy image devsecops-app
